# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
r_binary_packages:
  - Rcpp
  - dplyr
  - testthat
bioc_packages: GenomicRanges

r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr);codecov()'
